---
default:
    version: 1.03
    logging:
        log_dir: runtime
        log_file: app.log
        log_level:
            production: info
            development: debug
        alert_email:
            - g@cbqz.org
        filter:
            - email
    data: data # location for "data" directory
    optional_include: runtime/config.yaml
    mojolicious:
        session_cookie_name: cbqz
        secrets:
            - acf4631c010fbe6dc0e72b3a8930ebdb
            - 1fb07ba01a3c9f04bf716c28fac3bf15
        config:
            hypnotoad:
                proxy: 1
                workers: 10
                pid_file: runtime/hypnotoad.pid
                listen:
                    - http://*:3000
        session_duration: 14400 # 4 hours
        access_log:
            production: access.log
            development: morbo.log
    template:
        compile_ext: .ttc
        compile_dir: runtime/ttc
        wrapper: wrapper.html.tt
        include_path:
            - templates/pages
            - templates/components
    database:
        dsn: dbi:mysql:dbname=
        dbname: cbqz
        username: cbqz
        password: cbqz
        settings:
            AutoCommit: 1
            RaiseError: 1
            PrintError: 0
            mysql_enable_utf8: 1
            mysql_auto_reconnect: 1
        logging:
            debug: 1
            file: runtime/dbic_sql.sql
            profile: console
    recaptcha:
        public_key: 6LeGUjEUAAAAAHGfypaiPnD3r32I8sp7a8QeqYQg
        private_key: 6LftUTEUAAAAAKk9ZR886rf0l-3CuFzV_hTkt8gq
+|+|production:
    database:
        logging: ~
    logging:
        filter: ~
    recaptcha:
        public_key: 6LftUTEUAAAAALtbl98u4t4udXIAh9YpVnYRPdoP
        private_key: 6LeGUjEUAAAAAFvCPhrKLU0q5k7hlPS9toYr_Kl3
