---
default:
    version: 1.00
    logging:
        log_dir: runtime
        log_file: app.log
        log_level:
            production: info
            development: debug
        alert_email:
            - g@cbqz.org
    data: data
    optional_include: runtime/config.yaml
+|+|dev:
    logging:
        filter:
            - email
