# dest.prereq: config/changes/1472567336_db_create

CREATE TABLE socket (
    socket_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NULL,
    counter INTEGER UNSIGNED NOT NULL DEFAULT 0,
    data MEDIUMTEXT NULL,
    last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created TIMESTAMP NOT NULL DEFAULT '1970-01-01 08:00:00',
PRIMARY KEY(socket_id),
UNIQUE INDEX name(name)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TRIGGER socket_before_insert BEFORE INSERT ON socket FOR EACH ROW SET NEW.created = NOW();
